// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeSC1m-zVp90QAVC_-aTCZkofWs683Bp4',
    appId: '1:265632125633:web:88dda38a5fc93894c2ba40',
    messagingSenderId: '265632125633',
    projectId: 'emimbacke',
    authDomain: 'emimbacke.firebaseapp.com',
    databaseURL: 'https://emimbacke-default-rtdb.firebaseio.com',
    storageBucket: 'emimbacke.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBygdHfe_GoR4yZYp52JvrJBZWVngxbI94',
    appId: '1:265632125633:android:398b81b7d93885d0c2ba40',
    messagingSenderId: '265632125633',
    projectId: 'emimbacke',
    databaseURL: 'https://emimbacke-default-rtdb.firebaseio.com',
    storageBucket: 'emimbacke.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXDhrCoI9ZpJuhXK0dlU58RCD32GMeOq4',
    appId: '1:265632125633:ios:02075add332313f9c2ba40',
    messagingSenderId: '265632125633',
    projectId: 'emimbacke',
    databaseURL: 'https://emimbacke-default-rtdb.firebaseio.com',
    storageBucket: 'emimbacke.appspot.com',
    iosBundleId: 'com.example.emim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXDhrCoI9ZpJuhXK0dlU58RCD32GMeOq4',
    appId: '1:265632125633:ios:9f1d844e64266ae7c2ba40',
    messagingSenderId: '265632125633',
    projectId: 'emimbacke',
    databaseURL: 'https://emimbacke-default-rtdb.firebaseio.com',
    storageBucket: 'emimbacke.appspot.com',
    iosBundleId: 'com.example.emim.RunnerTests',
  );
}
